# Generated by Django 3.2.7 on 2022-03-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
