# Generated by Django 3.2.7 on 2022-03-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Name',
            new_name='FirstName',
        ),
        migrations.AddField(
            model_name='author',
            name='LastName',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='Patronymic',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
