# Generated by Django 3.2.7 on 2022-03-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20220308_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='FirstName',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='author',
            name='LastName',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='author',
            name='Patronymic',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
