# Generated by Django 3.2.7 on 2022-03-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_auto_20220308_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Photo',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
