# Generated by Django 3.2.7 on 2022-03-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_auto_20220308_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.ManyToManyField(blank=True, null=True, related_name='books', to='Store.Author'),
        ),
    ]
