# Generated by Django 3.2.7 on 2022-03-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='FirstName',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='author',
            name='LastName',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='author',
            name='Patronymic',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.ManyToManyField(blank=True, default='', related_name='books', to='Store.Author'),
        ),
    ]
