# Generated by Django 3.2.7 on 2022-03-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_auto_20220309_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
