# Generated by Django 3.2.7 on 2022-03-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='addedShoplist',
        ),
    ]
