# Generated by Django 3.2.7 on 2022-03-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_remove_book_addedshoplist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Active',
        ),
        migrations.RemoveField(
            model_name='book',
            name='PostedTime',
        ),
    ]
