# Generated by Django 3.2.7 on 2022-03-20 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_remove_book_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Poster',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='postedBooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
